### ISSUE TITLE
Promise related warning

### ISSUE THREAD

**Issue by krisnod** [Munter/express-systemjs-translate#210]
Warning: a promise was created in a handler at node_modules/express-systemjs-translate/lib/index.js:366:15 but was not returned from it, see http://goo.gl/rRqMUw
    at Promise._then (node_modules/bluebird/js/release/promise.js:231:17)

**Comment by Munter** [comment]
Do you have a setup where I can recreate this problem? I would also take a PR for a test that shows the error
